# Generated by Django 2.2.1 on 2019-05-18 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Birthplace', models.CharField(max_length=50)),
                ('Born', models.IntegerField()),
                ('Death', models.IntegerField()),
                ('Movement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('type_of_art', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('for_sale', models.CharField(max_length=3)),
                ('gallery_code', models.IntegerField()),
                ('artist_unique_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PostCode', models.IntegerField()),
                ('country', models.CharField(max_length=15)),
                ('director', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
