# Generated by Django 2.2.1 on 2019-05-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190518_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Born',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Death',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='gallery_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='PostCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
    ]
