# Generated by Django 2.1.7 on 2019-05-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Birthplace', models.CharField(max_length=50)),
                ('Born', models.CharField(max_length=50)),
                ('Death', models.CharField(max_length=50)),
                ('Movement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('type_of_art', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('for_sale', models.CharField(max_length=3)),
                ('artist_unique_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PostCode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=15)),
                ('director', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='gallery_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.Gallery'),
        ),
    ]
